### ISSUE TITLE
Missing a few imports

### ISSUE THREAD

**Issue by Brade** [peterbourgon/how-i-start-go#1]
Went thru this tutorial today and enjoyed it! 
I especially like how it gave a practical example for using goroutines & channels.

Only problem I noticed is that near the end of the tutorial here: http://howistart.org/posts/go/1
your code won't compile because you use the "time" and "log" variables without ever specifying the import statements for either one. This isn't necessarily the worst thing in the world, since it gets people to think more carefully about what they're doing (kinda like my college professors LOVED to do). But just in case you weren't aware, I thought I'd post here.

**Comment by tomazbracic** [comment]
The code doesn't work. It is broken. 
I keep getting 404 not found??

**Comment by peterbourgon** [comment]
Those excerpts aren't intended to be complete examples. See this repo for a runnable verison.
