### ISSUE TITLE
http://openweathermap.org/api requires API key now

### ISSUE THREAD

**Issue by tjaensch** [peterbourgon/how-i-start-go#3]
This function won't work anymore as is without API key:

func (w openWeatherMap) temperature(city string) (float64, error) {
    resp, err := http.Get("http://api.openweathermap.org/data/2.5/weather?q=" + city)
    if err != nil {
        return 0, err
    }

**Comment by gliptak** [comment]
https://www.howistart.org/posts/go/1 was already updated with OWM key
